
development:
  adapter: pg
  encoding: utf8
  database: etype_development
  pool: 5
  username: root
  password:
  socket: /tmp/mysql.sock

test:
  adapter: pg
  encoding: utf8
  database: etype_test
  pool: 5
  username: root
  password:
  socket: /tmp/mysql.sock

production:
  adapter: pg
  encoding: utf8
  database: etype_production
  pool: 5
  username: root
  password:
  socket: /tmp/mysql.sock
