development:
  adapter: mysql2
  encoding: utf8
  database: etype-development
  host: localhost
  username: root
  password:

test:
  adapter: mysql2
  encoding: utf8
  database: etype-test
  host: localhost
  username: root
  password:

production:
  adapter: mysql2
  encoding: utf8
  database: etype-production
  host: localhost
  username: root
  password:
